### ISSUE TITLE
Path fail on Windows

### ISSUE THREAD

**Issue by salvafern** [bio-oracle/pyo_oracle#4]
Hi, I see this:

```python

import pyo_oracle as po

constraints = {
    "time>=": "2000-01-01T00:00:00Z",
    "time<=": "2010-01-01T12:00:00Z",
    "time_step": 100,
    "latitude>=": 0,
    "latitude<=": 10,
    "latitude_step": 100,
    "longitude>=": 0,
    "longitude<=": 10,
    "longitude_step": 1
}

po.download_layers('phyc_baseline_2000_2020_depthmean', constraints = constraints)
#> Traceback (most recent call last):
#>   File "<stdin>", line 1, in <module>
#>   File "C:\pypkgs\pyo_oracle\pyo_oracle\main.py", line 28, in download_layers
#> _download_layer(dataset_id, output_directory, response, constraints, skip_confirmation, verbose, log, timestamp)
#> File "C:\pypkgs\pyo_oracle\pyo_oracle\utils.py", line 159, in _download_layer
#> logging.basicConfig(filename=logfile, format="%(asctime)s %(message)s", level=logging.INFO)
#> File "c:\users\salvadorf\appdata\local\programs\python\python37\Lib\logging\__init__.py", line 1895, in basicConfig
#> h = FileHandler(filename, mode)
#> File "c:\users\salvadorf\appdata\local\programs\python\python37\Lib\logging\__init__.py", line 1087, in __init__
#> StreamHandler.__init__(self, self._open())
#> File "c:\users\salvadorf\appdata\local\programs\python\python37\Lib\logging\__init__.py", line 1116, in _open    return open(self.baseFilename, self.mode, encoding=self.encoding)
#> OSError: [Errno 22] Invalid argument: 'C:\\pypkgs\\pyo_oracle\\pyo_oracle\\data\\phyc_baseline_2000_2020_depthmean_2023-04-20T14:19:59.log'
```
I think the log files cannot be read. Might be because the double "\\" that won't work on windows.

Info session

```python
import sys

sys.version
#> '3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]'

sys.implementation.name
#> 'cpython'

sys.platform
#> 'win32'
```

@vinisalazar could you have a look?

Thanks!

**Comment by salvafern** [comment]
I see:

```python
# Define constraints and download a layer
constraints = {
    "time>=": "2000-01-01T00:00:00Z",
    "time<=": "2010-01-01T12:00:00Z",
    "time_step": 100,
    "latitude>=": 0,
    "latitude<=": 10,
    "latitude_step": 100,
    "longitude>=": 0,
    "longitude<=": 10,
    "longitude_step": 1
}
pyo_oracle.download_layers("thetao_baseline_2000_2019_depthsurf", constraints=constraints)
# 
# Data directory is 'C:\pypkgs\pyo_oracle\pyo_oracle\data'.
# 
# You have 0 local datasets with the same preffix as 'thetao_baseline_2000_2019_depthsurf' in the data directory:
#   
#   You can check it again by running `list_local_data()`.
# To check the constraints of each existing dataset, see the log files in the data directory.
# 
# Would you like to proceed? y/Ny
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "C:\pypkgs\pyo_oracle\pyo_oracle\main.py", line 28, in download_layers
# _download_layer(dataset_id, output_directory, response, constraints, skip_confirmation, verbose, log, timestamp)
# File "C:\pypkgs\pyo_oracle\pyo_oracle\utils.py", line 159, in _download_layer
# logging.basicConfig(filename=logfile, format="%(asctime)s %(message)s", level=logging.INFO)
# File "c:\users\salvadorf\appdata\local\programs\python\python37\Lib\logging\__init__.py", line 1895, in basicConfig
# h = FileHandler(filename, mode)
# File "c:\users\salvadorf\appdata\local\programs\python\python37\Lib\logging\__init__.py", line 1087, in __init__
# StreamHandler.__init__(self, self._open())
# File "c:\users\salvadorf\appdata\local\programs\python\python37\Lib\logging\__init__.py", line 1116, in _open
# return open(self.baseFilename, self.mode, encoding=self.encoding)
# OSError: [Errno 22] Invalid argument: 'C:\\pypkgs\\pyo_oracle\\pyo_oracle\\data\\thetao_baseline_2000_2019_depthsurf_2023-06-20T08:56:23.log'

```

**Comment by vinisalazar** [comment]
@salvafern are you sure your installation is up-to-date?

**Comment by salvafern** [comment]
True, it was that. Fixed now, thanks!
